# Assignment

### This is the final that i was able to run other codes i tried were either incomplete or had errors,
### see Assignment try.ipynb

In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from PIL import Image as im

list1=[]
for i in range(20):
    im1=(im.open('picture\\'+str(i+1)+'.jpg'))
    im1=im1.resize((200,200),im.ANTIALIAS)
#    print(plt.imshow(im1))
    im1.save('resize'+str(i+1)+'.jpg')
    list1.append(np.array(im1))
#    print(a1)

for i in range(20):
    print(list1[i])

[[[ 82 110 139]
  [100 136 173]
  [121 170 218]
  ...
  [238 248 254]
  [238 248 254]
  [239 247 253]]

 [[ 98 133 169]
  [113 157 201]
  [123 173 224]
  ...
  [225 251 255]
  [226 251 255]
  [226 251 254]]

 [[117 163 210]
  [121 170 221]
  [121 172 222]
  ...
  [216 250 254]
  [217 250 254]
  [217 250 254]]

 ...

 [[ 57  69  82]
  [ 55  69  82]
  [ 54  67  80]
  ...
  [ 35  44  52]
  [ 35  43  51]
  [ 36  43  52]]

 [[ 52  64  76]
  [ 53  66  77]
  [ 54  66  77]
  ...
  [ 35  44  53]
  [ 35  45  53]
  [ 35  44  52]]

 [[ 53  66  79]
  [ 53  65  77]
  [ 52  64  76]
  ...
  [ 35  44  52]
  [ 36  45  52]
  [ 35  44  52]]]
[[[247 242 241 186]
  [247 242 240 185]
  [247 242 240 182]
  ...
  [240 234 234 164]
  [237 227 226 159]
  [244 235 233 157]]

 [[248 244 243 185]
  [248 243 240 186]
  [248 242 240 185]
  ...
  [235 230 230 172]
  [232 223 222 167]
  [242 232 230 164]]

 [[248 243 242 184]
  [248 242 240 183]
  [248 242 240 181]
  ...
  [239 233 233 169]
  [239 229 228 163]
  [240 2